### ISSUE TITLE
Piper error/not working after update

### ISSUE THREAD

**Issue by toddpage** [slackr31337/wyoming-piper-gpu#12]
Updated to the latest version and now I am getting the following error:

```
piper         | Traceback (most recent call last):
piper         |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
piper         |     return _run_code(code, main_globals, None,
piper         |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
piper         |     exec(code, run_globals)
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py", line 228, in <module>
piper         |     run()
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py", line 223, in run
piper         |     asyncio.run(main())
piper         |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
piper         |     return loop.run_until_complete(main)
piper         |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
piper         |     return future.result()
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py", line 191, in main
piper         |     await process_manager.get_process()
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/process.py", line 159, in get_process
piper         |     proc=await asyncio.create_subprocess_exec(
piper         |   File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
piper         |     transport, protocol = await loop.subprocess_exec(
piper         |   File "/usr/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
piper         |     transport = await self._make_subprocess_transport(
piper         |   File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
piper         |     transp = _UnixSubprocessTransport(self, protocol, args, shell,
piper         |   File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
piper         |     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
piper         |   File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
piper         |     self._proc = subprocess.Popen(
piper         |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
piper         |     self._execute_child(args, executable, preexec_fn, close_fds,
piper         |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
piper         |     raise child_exception_type(errno_num, err_msg, err_filename)
piper         | FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/piper/piper'
```
Here is my compose data:
```
  piper:  
    #image: homeassistant/amd64-addon-piper:latest  
    image: slackr31337/wyoming-piper-gpu:latest 
    container_name: piper  

    entrypoint: python3  
    command: >  
      -m wyoming_piper  
      --piper '/usr/share/piper/piper'  
      --uri 'tcp://0.0.0.0:10200'  
      --length-scale "1"  
      --noise-scale "0.667"  
      --speaker "0"  
      --voice "en_US-amy-medium"  
      --max-piper-procs "1"  
      --data-dir /data  
      --data-dir /share/piper  
      --download-dir /data  
#      --device cuda
    ports:  
      - 10200:10200  
    environment:  
      - TZ=America/Chicago  
    volumes:  
      - /opt/voiceAssistant/piper-data:/data  
      - /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcublasLt.so.11:/usr/lib/x86_64-linux-gnu/libcublasLt.so.12:ro
      - /usr/lib/x86_64-linux-gnu/libcublas.so.11:/usr/lib/x86_64-linux-gnu/libcublas.so.12:ro
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute
```

Everything was working until the update;

Thanks.
