### ISSUE TITLE
Piper error/not working after update - Reff #12

### ISSUE THREAD

**Issue by toddpage** [slackr31337/wyoming-piper-gpu#18]
With version v2023.12.0 I get
piper         | /usr/bin/python3: No module named wyoming_piper 
With latest version I get:

```
piper exited with code 1
piper         | Traceback (most recent call last):
piper         |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
piper         |     return _run_code(code, main_globals, None,
piper         |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
piper         |     exec(code, run_globals)
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py", line 228, in <module>
piper         |     run()
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py", line 223, in run
piper         |     asyncio.run(main())
piper         |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
piper         |     return loop.run_until_complete(main)
piper         |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
piper         |     return future.result()
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py", line 191, in main
piper         |     await process_manager.get_process()
piper         |   File "/usr/local/lib/python3.10/dist-packages/wyoming_piper/process.py", line 159, in get_process
piper         |     proc=await asyncio.create_subprocess_exec(
piper         |   File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
piper         |     transport, protocol = await loop.subprocess_exec(
piper         |   File "/usr/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
piper         |     transport = await self._make_subprocess_transport(
piper         |   File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
piper         |     transp = _UnixSubprocessTransport(self, protocol, args, shell,
piper         |   File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
piper         |     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
piper         |   File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
piper         |     self._proc = subprocess.Popen(
piper         |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
piper         |     self._execute_child(args, executable, preexec_fn, close_fds,
piper         |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
piper         |     raise child_exception_type(errno_num, err_msg, err_filename)
piper         | FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/piper/piper'
piper exited with code 1

```

Still using same compose code.

---------------------------------------------------

With version v2025.01.3

```

piper exited with code 0
piper         | /usr/bin/python3: No module named wyoming_piper
whisper       | INFO:__main__:Ready
whisper       | Connection to localhost (127.0.0.1) 10300 port [tcp/*] succeeded!
whisper       | [ls.io-init] done.
piper exited with code 0
piper         | /usr/bin/python3: No module named wyoming_piper
piper exited with code 1
piper         | /usr/bin/python3: No module named wyoming_piper
piper exited with code 1
piper         | /usr/bin/python3: No module named wyoming_piper
piper exited with code 1
piper         | /usr/bin/python3: No module named wyoming_piper
piper exited with code 1

```

**Comment by slackr31337** [comment]
Hello,

I've made some progress on the Docker image and released an update. Can you test it out?

https://github.com/slackr31337/wyoming-piper-gpu/releases/tag/v2025.01.6

**Comment by toddpage** [comment]
Getting the following error now:

```
piper exited with code 0
piper         | /bin/python3: No module named wyoming_piper
piper exited with code 1
piper         | /bin/python3: No module named wyoming_piper

```

docker-compose:

```
  piper:  
    #image: homeassistant/amd64-addon-piper:latest  
    image: slackr31337/wyoming-piper-gpu:v2025.01.6
    container_name: piper  

    entrypoint: python3  
    command: >  
      -m wyoming_piper  
      --piper '/usr/share/piper/piper'  
      --uri 'tcp://0.0.0.0:10200'  
      --length-scale "1"  
      --noise-scale "0.667"  
      --speaker "0"  
      --voice "en_US-amy-medium"  
      --max-piper-procs "1"  
      --data-dir /data  
      --data-dir /share/piper  
      --download-dir /data  
    ports:  
      - 10200:10200  
    environment:  
      - TZ=America/Chicago  
    volumes:  
      - /opt/voiceAssistant/piper-data:/data  
      - /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcublasLt.so.11:/usr/lib/x86_64-linux-gnu/libcublasLt.so.12:ro
      - /usr/lib/x86_64-linux-gnu/libcublas.so.11:/usr/lib/x86_64-linux-gnu/libcublas.so.12:ro
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute

```


```
Sun Jan 12 17:21:02 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A2000 12GB          On  | 00000000:01:00.0 Off |                  Off |
| 30%   54C    P0              23W /  70W |    111MiB / 12282MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      5732      G   /usr/lib/xorg/Xorg                           46MiB |
|    0   N/A  N/A      5854      G   /usr/bin/gnome-shell                         42MiB |
+---------------------------------------------------------------------------------------+

```
