### ISSUE TITLE
Custom voices

### ISSUE THREAD

**Issue by toddpage** [slackr31337/wyoming-piper-gpu#24]
Trying to add custom voices with no luck

**Comment by toddpage** [comment]
Error:

```
piper         | Traceback (most recent call last):
piper         |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
piper         |     return _run_code(code, main_globals, None,
piper         |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
piper         |     exec(code, run_globals)
piper         |   File "/app/lib/python3.10/site-packages/wyoming_piper/__main__.py", line 242, in <module>
piper         |     run()
piper         |   File "/app/lib/python3.10/site-packages/wyoming_piper/__main__.py", line 237, in run
piper         |     asyncio.run(main())
piper         |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
piper         |     return loop.run_until_complete(main)
piper         |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
piper         |     return future.result()
piper         |   File "/app/lib/python3.10/site-packages/wyoming_piper/__main__.py", line 157, in main
piper         |     custom_voice_path, custom_config_path = find_voice(
piper         |   File "/app/lib/python3.10/site-packages/wyoming_piper/download.py", line 183, in find_voice
piper         |     raise VoiceNotFoundError(name)
piper         | wyoming_piper.download.VoiceNotFoundError: "en_US-myvoice-high"

```

docker-compose.yaml

```
  piper:  
    image: slackr31337/wyoming-piper-gpu:latest
    container_name: piper  
    ports:  
      - 10200:10200  
    environment:  
      - TZ=America/Chicago  
      - PIPER_VOICE="en_US-myvoice-high"
    volumes:  
      - /opt/voiceAssistant/piper-data:/data  
	#  - /opt/voiceAssistant/piper-data/voices.json:/usr/local/lib/python3.10/site-packages/wyoming_piper/voices.json:ro 
    #  - /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8:ro
    #  - /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8:ro
    #  - /usr/lib/x86_64-linux-gnu/libcublasLt.so.11:/usr/lib/x86_64-linux-gnu/libcublasLt.so.12:ro
    #  - /usr/lib/x86_64-linux-gnu/libcublas.so.11:/usr/lib/x86_64-linux-gnu/libcublas.so.12:ro
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute
```
