### ISSUE TITLE
CUDA doesn't work

### ISSUE THREAD

**Issue by OperKH** [slackr31337/wyoming-piper-gpu#7]
Looks like this image doesn't utilise GPU

When I try voice in home assistant with a long text e.g. fairy tale I see high CPU utilisation, and my GPU is idle.

Here is my config:
### docker-compose.yml
```yaml
version: "3.8"

name: home-assistant-addons

services:
  piper-gpu:
    container_name: piper-gpu
    image: ghcr.io/slackr31337/wyoming-piper-gpu:latest
    ports:
      - 10200:10200
    volumes:
      - /srv/appdata/piper-gpu/data:/data
    command: --voice uk_UA-ukrainian_tts-medium
    extends:
      file: hwaccel.yml
      service: cuda
    restart: always

  whisper-gpu:
    container_name: whisper-gpu
    image: ghcr.io/slackr31337/wyoming-whisper-gpu:latest
    ports:
      - 10300:10300
    volumes:
      - /srv/appdata/whisper-gpu/data:/data
    command: --model medium-int8 --language uk --beam-size 5 --device cuda
    extends:
      file: hwaccel.yml
      service: cuda
    restart: always
```

### hwaccel.yml
```yaml
version: "3.8"

services:
  cuda:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA
```

When I run `nvidia-smi` I see that only whisper process is runnng, and never saw any other process on GPU
```text
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
|  0%   54C    P8    16W / 230W |   1142MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1507263      C   python3                          1138MiB |
+-----------------------------------------------------------------------------+
```

**Comment by neowisard** [comment]
> Looks like this image doesn't utilise GPU
You can try this https://github.com/Navatusein/Silero-TTS-Service , it work with UA and you can make docker for Cuda .

**Comment by sarpba** [comment]
Just piper but working for me with this compose:
```
version: "3.8"

services:
  piper-gpu:
    container_name: piper-gpu
    image: ghcr.io/slackr31337/wyoming-piper-gpu:latest
    ports:
      - 10200:10200
    volumes:
      - /srv/appdata/piper-gpu/data:/data
    restart: always
    command: --voice uk_UA-ukrainian_tts-medium
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
